DELIMITER $$

CREATE DATABASE IF NOT EXISTS BBOG_KATA_CODE_CONVERTER$$

USE BBOG_KATA_CODE_CONVERTER$$

CREATE TABLE IF NOT EXISTS CODE_CONVERSION (
    
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    SOURCE_LANGUAGE     ENUM('Delphi','COBOL') NOT NULL COMMENT 'source code language', 
    TARGET_LANGUAGE     ENUM('Java','Node.js','Python','GO') NOT NULL COMMENT 'target code language',
    INPUT_CODE          LONGTEXT NOT NULL,
    OUTPUT_CODE         LONGTEXT NULL,
    CONVERSION_STATUS   ENUM('PENDING','SUCCESS','FAILED') DEFAULT 'PENDING',
    ERROR_MESSAGE       VARCHAR(512) NULL,
    REQUEST_ID          VARCHAR(100) NULL,
    IP                  VARCHAR(45) NOT NULL,
    CREATED             DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED            DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY          VARCHAR(100) NULL
)$$

create index IX_SOURCE_LANGUAGE
    on CODE_CONVERSION (SOURCE_LANGUAGE)$$

CREATE TRIGGER TR_MODIFIED_CODE_CONVERTION
BEFORE UPDATE ON CODE_CONVERSION
FOR EACH ROW
BEGIN
    SET NEW.MODIFIED = NOW();
END$$

DELIMITER ;